[package]
name = "jsonview"
version = "0.1.3"
description = "JSON 妗岄潰闃呰鍣?
authors = ["You"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "0.1.3", features = [] }

[dependencies]
serde = { version = "0.1.3", features = ["derive"] }
serde_json = "1.0"
# 闇€瑕佸紑鍚?devtools 鐗规€э紝鎵嶈兘鍦?Rust 绔皟鐢?open_devtools()
tauri = { version = "0.1.3", features = ["devtools"] }
tauri-plugin-dialog = "2.0"
tauri-plugin-single-instance = "2.3.7"
url = "2.5"

[profile.release]
opt-level = "s"





